#!/usr/bin/env python

import os
import sys
import time
import uuid
import base64
import tempfile
import httplib
import urllib
import json

def ci_push(db_url, git_url, changeset_base_url, tree_base_url, test_path, sha, author, message, headers):
    # construct json documents
    docs = []

    # record (revision) document
    record = {
        '_id': sha,
        'type': 'record',
        'description': message,
        'created': time.time(),
        'author': author,
        'changeset_url': changeset_base_url + sha
    }

    docs.append(record)

    # cppcheck task document
    cppcheck = {
        '_id': uuid.uuid4().get_hex(),
        'type': 'task',
        'name': 'cppcheck',
        'created': time.time(),
        'platform': 'linux',
        'kwargs': {
            'sha': sha,
            'git_url': git_url
        },
        'record_id': sha
    }

    docs.append(cppcheck)

    # fixme detector task document
    fixme = {
        '_id': uuid.uuid4().get_hex(),
        'type': 'task',
        'name': 'fixme',
        'created': time.time(),
        'platform': 'linux',
        'kwargs': {
            'sha': sha,
            'git_url': git_url
        },
        'record_id': sha
    }

    docs.append(fixme)

    # get task names with github api
    tasknames = []
    conn = httplib.HTTPSConnection('api.github.com')
    req = conn.request('GET', tree_base_url + sha + '?' + urllib.urlencode({'recursive':1}), headers=headers)
    resp = conn.getresponse()
    tree = json.loads(resp.read())['tree']

    for item in tree:
        if item['type'] == 'tree' and item['path'][:len(test_path)] == test_path and item['path'] != test_path:
            tasknames.append(item['path'].split('/')[-1])

    # rattest task documents
    for taskname in tasknames:
        taskid = uuid.uuid4().get_hex()
        task = {
            '_id': uuid.uuid4().get_hex(),
            'type': 'task',
            'name': 'rattest',
            'created': time.time(),
            'platform': 'linux',
            'kwargs': {
                'sha': sha,
                'git_url' : git_url,
                'testname': taskname
            },
            'record_id': sha
        }

        docs.append(task)

    # post the docs with couch's bulk document api
    docs = {'docs': docs}
    conn = httplib.HTTPConnection(db_url)
    auth_string =  base64string = base64.encodestring('%s:%s' % (raw_input('Builder Username: '), getpass.getpass('Builder Password: ')))[:-1]
    headers = {'Content-type': 'application/json', 'Authorization': 'Basic %s' % auth_string}
    conn.request("POST", "/pytunia-ondemand/_bulk_docs", json.dumps(docs), headers=headers)
    print 'Server response:', conn.getresponse().status

    results_url = '/pytunia-ondemand/_design/pytunia/_rewrite/record/'
    print 'View results at http://' + db_url + results_url + sha

if __name__ == '__main__':
    import optparse
    import getpass

    test_path = 'test/full'
    parser = optparse.OptionParser()
    parser.add_option('-s', '--server', dest='server', default='localhost:5984')
    parser.add_option('-r', '--repository', dest='repo', default='DEFAULT_REPO')
    parser.add_option('-b', '--branch', dest='branch', default='master')
    parser.add_option('-m', '--message', dest='message', default='No description')
    (options, args) = parser.parse_args()

    # get sha for latest commit
    conn = httplib.HTTPSConnection('api.github.com')
    gh_user = raw_input('GitHub Username: ')
    auth_string =  base64string = base64.encodestring('%s:%s' % (gh_user, getpass.getpass('GitHub Password: ')))[:-1]
    headers = {'Content-type': 'application/json', 'Authorization': 'Basic %s' % auth_string}
    conn.request('GET', '/repos/%s/%s/branches' % (gh_user, options.repo), headers=headers)
    branches = json.loads(conn.getresponse().read())

    sha = None
    for branch in branches:
        try:
            if branch['name'] == options.branch:
                sha = branch['commit']['sha']
                break
        except TypeError:
            print 'Unable to access branches for %s/%s' % (gh_user, options.repo)
            sys.exit(1)

    if sha is None:
        print 'Error finding commit data for branch', options.branch
        sys.exit(1)

    # chance to abort
    if raw_input('Run build tests on %s/%s/%s @ %s? y/[n] ' % (gh_user, options.repo, options.branch, sha)) != 'y':
        sys.exit(0)

    # push to the pytunia server
    git_url = 'git@github.com:%s/%s' % (gh_user, options.repo)
    changeset_base_url = 'https://github.com/%s/%s/commit/' % (gh_user, options.repo)
    tree_base_url = '/repos/%s/%s/git/trees/' % (gh_user, options.repo)

    ci_push(options.server, git_url, changeset_base_url, tree_base_url, test_path, sha, gh_user, options.message, headers)

